# ARRAY CREATION

In [1]:
# import numpy library
import numpy as np

ARRAY DIMENSIONS

In [2]:
# 0D-ARRAY
# also called SCALARS (no axis, not even row or column, example temperature age height...)
arr0 = np.array([1,])
print("0D ARRAY")
print(arr0)
print(arr0.shape)
print("\n")
# =================================================================================================================

# 1D-ARRAY
# also called VECTORS (only one axis, either row or column)
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("1D ARRAY")
print(arr1)
print(arr1.shape)
print("\n")
# =================================================================================================================

# 2D-ARRAY
# also called MATRICES (two axis, row and column)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D ARRAY")
print(arr2)
print(arr2.shape)
print("\n")
# =================================================================================================================

# 3D-ARRAY
# also calles TENSORS (three axis, depth, row and column)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D ARRAY")
print(arr3)
print(arr3.shape)
print("\n")

0D ARRAY
[1]
(1,)


1D ARRAY
[1 2 3 4 5 6]
(6,)


2D ARRAY
[[1 2 3]
 [4 5 6]]
(2, 3)


3D ARRAY
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)




ACCESSING ARRAY ITEMS

In [3]:
# ACCESS FROM 0D ARRAY
# only 1 element so only 0 index
print(arr0[0])
# =================================================================================================================

# ACCESS FROM 1D ARRAY
# 2 index mean 3rd element
print(arr1[2])
# =================================================================================================================

# ACCESS FROM 2D ARRAY
# first row index, then column index
# (2,1 formula)
print(arr2[1, 0])
# =================================================================================================================

# ACCESS FROM 3D ARRAY
# first depth index, then row index, then column index
# (3,2,1 formula)
print(arr3[0, 1, 0])

1
3
4
3


NP.ARRAY()

In [4]:
# np.array(object, dtype=None, copy=True, ndmin=0)
# =================================================================================================================

# OBJECT (required): Input data (list, tuple, or array-like)
# DTYPE (optional): Desired data type (int, float, double, str, complex)
# COPY (optional): Default Value is (True) means create new copy (change in new copy array can't change in the orignal list or tuple) and (False) mean view (change made on array also changes orignal list or tuple)
# NDMIN (optional): Minimum number of dimensions
# =================================================================================================================

# Create array from tuple, list ...
# RETURNS n dimensional array (store or print it)
# =================================================================================================================

# ARRAY BY LIST (directly)
arr = np.array([1, 2, 3])
print(arr)
# ARRAY BY LIST (through variable)
list = [1, 2, 3]
arr = np.array(list)
print(arr)
print("\n")
# =================================================================================================================


# DTYPE PARAMETER
arr = np.array([1, 2, 3], dtype = 'float')
print(arr)

arr = np.array([1, 2, 3], dtype = 'int')
print(arr)

arr = np.array([1, 2, 3], dtype = 'bool')
print(arr)

arr = np.array([1, 2, 3], dtype = 'str')
print(arr)
print("\n")
# =================================================================================================================

# COPY PARAMETER
a1 = np.array([1, 2, 3])
arr = np.array(a1, copy = True)
arr[0] = 7
print(a1) # list not changes by copy=True
print(arr) # COPY
print("\n")

a1 = np.array([1, 2, 3])
arr = np.array(a1, copy = False)
arr[0] = 7
print(a1) #list changes by copy=False
print(arr) # VIEW
print("\n")
# =================================================================================================================

# NDIM PARAMETER
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=1)
print(arr.shape)
print(arr)
print("\n")

arr = np.array([1, 2, 3, 4, 5, 6], ndmin=3)
print(arr.shape)
print(arr)
print("\n")

[1 2 3]
[1 2 3]


[1. 2. 3.]
[1 2 3]
[ True  True  True]
['1' '2' '3']


[1 2 3]
[7 2 3]


[7 2 3]
[7 2 3]


(6,)
[1 2 3 4 5 6]


(1, 1, 6)
[[[1 2 3 4 5 6]]]




NP.ASARRAY()

In [ ]:
# np.asarray(object, dtype=None)
# =================================================================================================================

# MAIN FEATURE: 
# It converts input to an array, but it DOES NOT COPY if the input is already an array
# It is faster and saves memory compared to np.array()
# =================================================================================================================

# CREATING ARRAY FROM LIST OR TUPLE
# (Acts just like np.array for basic lists)
my_list = [1, 2, 3]
arr = np.asarray(my_list)
print("From List:", arr)
# =================================================================================================================

# np.array: Always makes a NEW copy (by default)
# np.asarray: Only makes a copy if necessary. If input is already an array, it uses the SAME memory

# initial array
original = np.array([1, 2, 3])
print("Original Array:", original)

# CASE A: Using np.array (Creates a Copy)
arr_copy = np.array(original)
arr_copy[0] = 500
print("Original after np.array change:", original) # Original stays [1, 2, 3] (Safe)

# CASE B: Using np.asarray (Creates a View/Reference)
arr_view = np.asarray(original)
arr_view[0] = 9
print("Original after np.asarray change:", original) # Original CHANGES to [999, 2, 3] (Shared Memory)
print("\n")

From List: [1 2 3]
Original Array: [1 2 3]
Original after np.array change: [1 2 3]
Original after np.asarray change: [9 2 3]




NP.ASANYARRAY()

In [ ]:
# np.asanyarray(object, dtype=None)
# =================================================================================================================

# MAIN FEATURE:
# It converts input to an array, but it PRESERVES subclasses of ndarray (like matrix, masked array)
# It does NOT copy if the input is already an ndarray or its subclass
# =================================================================================================================

# DIFFERENCE SUMMARY:
# np.array      -> Always returns a base ndarray (copies by default)
# np.asarray    -> Returns ndarray, may discard subclass
# np.asanyarray -> Returns ndarray OR keeps subclass (best for generic code)
# =================================================================================================================

# CREATING ARRAY FROM LIST OR TUPLE
# (Acts just like np.array / np.asarray for basic lists)
my_list = [1, 2, 3]
arr = np.asanyarray(my_list)
print("From List:", arr, "\n")
# =================================================================================================================

# USING WITH NORMAL ndarray
original = np.array([1, 2, 3])
print("Original Array:", original)

# np.asanyarray DOES NOT COPY if input is already an ndarray
arr_view = np.asanyarray(original)
arr_view[0] = 5
print("Original after np.asanyarray change:", original, "\n")  # Original CHANGES (shared memory)
# =================================================================================================================

# SUBCLASS PRESERVATION (KEY FEATURE)
# Example: numpy matrix (subclass of ndarray)
mat = np.matrix([[1, 2], [3, 4]])
print("Original Matrix:\n", mat)
print("Original Type:", type(mat))

# Using np.asarray (SUBCLASS LOST)
asarray_result = np.asarray(mat)
print("\nUsing np.asarray:")
print(asarray_result)
print("Type:", type(asarray_result))  # becomes ndarray

# Using np.asanyarray (SUBCLASS PRESERVED)
asanyarray_result = np.asanyarray(mat)
print("\nUsing np.asanyarray:")
print(asanyarray_result)
print("Type:", type(asanyarray_result))  # remains matrix
# =================================================================================================================

# WHEN TO USE np.asanyarray:
# ✔ When writing library / reusable code
# ✔ When you want to accept ndarray subclasses safely
# ✔ When you want performance (no unnecessary copy)

From List: [1 2 3] 

Original Array: [1 2 3]
Original after np.asanyarray change: [5 2 3] 

Original Matrix:
 [[1 2]
 [3 4]]
Original Type: <class 'numpy.matrix'>

Using np.asarray:
[[1 2]
 [3 4]]
Type: <class 'numpy.ndarray'>

Using np.asanyarray:
[[1 2]
 [3 4]]
Type: <class 'numpy.matrix'>


NP.ASCONTIGOUSARRAY()

In [ ]:
# np.ascontiguousarray(object, dtype=None)
# =================================================================================================================

# MAIN FEATURE:
# It converts input to a C-CONTIGUOUS array (row-major memory layout)
# It makes a COPY ONLY IF the input array is NOT already contiguous
# This is important for performance in low-level operations
# =================================================================================================================

# WHY CONTIGUOUS MEMORY MATTERS:
# Many NumPy operations, C extensions, and libraries expect data to be stored sequentially in memory for speed
# =================================================================================================================

# CREATING ARRAY FROM LIST OR TUPLE
# (Creates a contiguous array by default)
my_list = [1, 2, 3]
arr = np.ascontiguousarray(my_list)
print("From List:", arr)
print("Is Contiguous:", arr.flags['C_CONTIGUOUS'])
# =================================================================================================================

# CASE A: ALREADY CONTIGUOUS ARRAY (NO COPY)
original = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("\nOriginal Array:\n", original)
print("Is Contiguous:", original.flags['C_CONTIGUOUS'])

contig_arr = np.ascontiguousarray(original)
contig_arr[0, 0] = 99

print("Original after ascontiguousarray change:\n", original)   # Original CHANGES → shared memory (no copy made)
# =================================================================================================================

# CASE B: NON-CONTIGUOUS ARRAY (COPY REQUIRED)
# Example: Transposed array (NOT contiguous)
non_contig = original.T
print("\nTransposed Array:\n", non_contig)
print("Is Contiguous:", non_contig.flags['C_CONTIGUOUS'])

fixed_contig = np.ascontiguousarray(non_contig)
fixed_contig[0, 0] = 99

print("\nAfter np.ascontiguousarray:")
print("Fixed Array:\n", fixed_contig)
print("Original after fixing:\n", original)
# Original DOES NOT change → COPY was created
# =================================================================================================================

# COMPARISON SUMMARY:
# np.array              -> Always creates a new array (copy)
# np.asarray            -> No copy if input already ndarray
# np.asanyarray         -> No copy + preserves subclasses
# np.ascontiguousarray  -> No copy ONLY if already contiguous
# =================================================================================================================

# WHEN TO USE np.ascontiguousarray:
# ✔ When working with transposed / sliced arrays
# ✔ Before passing data to C / C++ / Cython / OpenCV
# ✔ When performance is critical

From List: [1 2 3]
Is Contiguous: True

Original Array:
 [[1 2 3]
 [4 5 6]]
Is Contiguous: True
Original after ascontiguousarray change:
 [[99  2  3]
 [ 4  5  6]]

Transposed Array:
 [[99  4]
 [ 2  5]
 [ 3  6]]
Is Contiguous: False

After np.ascontiguousarray:
Fixed Array:
 [[99  4]
 [ 2  5]
 [ 3  6]]
Original after fixing:
 [[99  2  3]
 [ 4  5  6]]


NP.ASMATRIX()

In [21]:
# np.asmatrix(object, dtype=None)
# =================================================================================================================

# MAIN FEATURE:
# It converts input into a NumPy matrix (np.matrix)
# It ALWAYS returns a 2-D matrix
# If the input is already a matrix, NO COPY is made
# np.matrix is a subclass of ndarray
# important for matrix-specific operations (like * for matrix multiplication)
# =================================================================================================================

# simple array from a list
my_list = [1, 2, 3]
arr = np.array(my_list)
print("From List:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
# matrix (2-D array) from a list
mat = np.asmatrix(my_list)
print("From List:\n", mat)
print("Shape:", mat.shape)
print("Type:", type(mat))
# =================================================================================================================

# CREATING MATRIX FROM 2-D LIST
my_2d_list = [[1, 2], [3, 4]]
mat2 = np.asmatrix(my_2d_list)
print("\nFrom 2-D List:\n", mat2)
print("Shape:", mat2.shape)
# =================================================================================================================

# USING WITH ndarray
arr = np.array([[5, 6], [7, 8]])
print("\nOriginal ndarray:\n", arr)
print("Original Type:", type(arr))

mat_from_arr = np.asmatrix(arr)
print("\nAfter np.asmatrix:\n", mat_from_arr)
print("Type:", type(mat_from_arr))
# =================================================================================================================

# SHARED MEMORY BEHAVIOR
# np.asmatrix does NOT copy data (when input is 2D array)
mat_from_arr[0, 0] = 99
print("\nOriginal ndarray after matrix change:\n", arr) # Original CHANGES → shared memory
# =================================================================================================================

# MATRIX-SPECIFIC OPERATIONS
# * operator means MATRIX MULTIPLICATION (not element-wise)
A = np.asmatrix([[1, 2], [3, 4]])
B = np.asmatrix([[5, 6], [7, 8]])

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)
print("A * B (Matrix Multiplication):\n", A * B)
# =================================================================================================================

# COMPARISON SUMMARY:
# np.array      -> Returns ndarray (any dimension)
# np.asarray    -> ndarray, no copy if possible
# np.asanyarray -> ndarray + keeps subclasses
# np.asmatrix   -> ALWAYS returns 2-D matrix (subclass of ndarray)


From List:
 [1 2 3]
Shape: (3,)
Type: <class 'numpy.ndarray'>
From List:
 [[1 2 3]]
Shape: (1, 3)
Type: <class 'numpy.matrix'>

From 2-D List:
 [[1 2]
 [3 4]]
Shape: (2, 2)

Original ndarray:
 [[5 6]
 [7 8]]
Original Type: <class 'numpy.ndarray'>

After np.asmatrix:
 [[5 6]
 [7 8]]
Type: <class 'numpy.matrix'>

Original ndarray after matrix change:
 [[99  6]
 [ 7  8]]

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A * B (Matrix Multiplication):
 [[19 22]
 [43 50]]


NP.IDENTITY()

In [24]:
# np.identity(n, dtype=None)
# =================================================================================================================

# N (required): Number of rows and columns (creates an n × n matrix)
# DTYPE (optional): Desired data type (int, float...)
# =================================================================================================================

# MAIN FEATURE:
# It creates a SQUARE IDENTITY MATRIX
# Diagonal elements = 1
# All other elements = 0
# =================================================================================================================

# INT IDENTITY MATRIX
I = np.identity(3, dtype=int)
print("3x3 Identity Matrix:\n", I)
print("Shape:", I.shape)
print("Type:", type(I))
# =================================================================================================================

# FLOAT IDENTITY MATRIX 
I_float = np.identity(4, dtype=float)
print("\n4x4 Identity Matrix (float):\n", I_float)
print("Data Type:", I_float.dtype)
# =================================================================================================================

# MATHEMATICAL PROPERTY
# Identity matrix acts like 1 in matrix multiplication
A = np.array([[2, 3],
              [4, 5]])
I2 = np.identity(2)

print("\nMatrix A:\n", A)
print("A * I (using @):\n", A @ I2)
print("I * A (using @):\n", I2 @ A)
# Result remains SAME as A
# =================================================================================================================

# COMPARISON WITH RELATED FUNCTIONS
# np.identity(n)      -> Square identity matrix only
# np.eye(n)           -> Square identity matrix (same result)
# np.eye(n, m)        -> Rectangular identity-like matrix
# =================================================================================================================

# WHEN TO USE np.identity:
# ✔ Linear algebra operations
# ✔ Initializing weights
# ✔ Matrix inversion checks
# ✔ Unit transformation matrix

3x3 Identity Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape: (3, 3)
Type: <class 'numpy.ndarray'>

4x4 Identity Matrix (float):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Data Type: float64

Matrix A:
 [[2 3]
 [4 5]]
A * I (using @):
 [[2. 3.]
 [4. 5.]]
I * A (using @):
 [[2. 3.]
 [4. 5.]]


NP.EYE()

In [29]:
# np.eye(N, M=None, k=0, dtype=None)
# =================================================================================================================

# N (required): Number of rows
# M (optional): Number of columns (default = N)
# K (optional): Diagonal index
#     k = 0  -> main diagonal
#     k > 0  -> above main diagonal
#     k < 0  -> below main diagonal
# DTYPE (optional): Desired data type (int, float, etc.)
# =================================================================================================================

# MAIN FEATURE:
# It creates a 2-D array with ones on a specified diagonal and zeros elsewhere
# Can create BOTH square and rectangular matrices
# =================================================================================================================

# BASIC SQUARE IDENTITY MATRIX
eye1 = np.eye(3, dtype=int)
print("3x3 Identity Matrix Using np.eye:\n", eye1)
print("Shape:", eye1.shape)
# =================================================================================================================

# RECTANGULAR MATRIX
eye2 = np.eye(3, 5, dtype=int)
print("\n3x5 Rectangular Matrix Using np.eye:\n", eye2)
print("Shape:", eye2.shape)
# =================================================================================================================

# USING DIAGONAL OFFSET (k)
# ABOVE MAIN DIAGONAL
eye_above = np.eye(4, k=1, dtype=int)
print("\nOnes above main diagonal (k=1):\n", eye_above)

# BELOW MAIN DIAGONAL
eye_below = np.eye(4, k=-1, dtype=int)
print("\nOnes below main diagonal (k=-1):\n", eye_below)
# =================================================================================================================

# SPECIFYING DATA TYPE
eye_float = np.eye(3, dtype=float)
print("\nEye Matrix with float dtype:\n", eye_float)
print("Data Type:", eye_float.dtype)
# =================================================================================================================

# COMPARISON SUMMARY
# np.identity(n)    -> Only square identity matrix
# np.eye(n)         -> Square identity matrix (same as np.identity)
# np.eye(n, m)      -> Square or rectangular (n=rows, m=columns)
# np.eye(n, m, k)   -> With diagonal offset (above/below main diagonal)
# =================================================================================================================

# WHEN TO USE np.eye:
# ✔ Creating identity matrices
# ✔ Creating diagonal masks
# ✔ Linear algebra operations
# ✔ Custom diagonal placement
# =================================================================================================================


3x3 Identity Matrix Using np.eye:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape: (3, 3)

3x5 Rectangular Matrix Using np.eye:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
Shape: (3, 5)

Ones above main diagonal (k=1):
 [[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]

Ones below main diagonal (k=-1):
 [[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]

Eye Matrix with float dtype:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Data Type: float64


NP.COPY()

In [35]:
# np.copy(a, order='K')
# =================================================================================================================

# A (required): Input array
# ORDER (optional): Controls how array elements are arranged in memory
#                  'C' → Stores data row by row (last index changes fastest), standard in Python
#                  'F' → Stores data column by column (first index changes fastest), used in Fortran
#                  'A' → Chooses 'F' if the input is already Fortran-contiguous, otherwise uses 'C'
#                  'K' → Preserves the original memory order as closely as possible (default)
# =================================================================================================================

# MAIN FEATURE:
# It creates a SHALLOW COPY of the array
# The new array has its OWN memory
# Changes to the copied array DO NOT affect the original array
# =================================================================================================================

# BASIC COPY
original = np.array([1, 2, 3])
copied = np.copy(original)

copied[0] = 99
print("Original Array:", original)
print("Copied Array:", copied)
# =================================================================================================================

# PROOF: MEMORY IS DIFFERENT
print("\nDo they share memory?")
print("Same object:", original is copied)
print("Same memory:", np.shares_memory(original, copied))
# =================================================================================================================

# COPYING MULTI-DIMENSIONAL ARRAY
arr2d = np.array([[1, 2],
                  [3, 4]])

arr2d_copy = np.copy(arr2d)
arr2d_copy[0, 0] = 10

print("\nOriginal 2D Array:\n", arr2d)    # Original remains unchanged
print("Copied 2D Array:\n", arr2d_copy)
# =================================================================================================================

# COPYING WITH MEMORY ORDER
# Fortran-ordered copy
f_copy = np.copy(arr2d, order='F')
print("\nFortran Ordered Copy:")
print("Is F-contiguous:", f_copy.flags['F_CONTIGUOUS'])
print("Is C-contiguous:", f_copy.flags['C_CONTIGUOUS'])
# =================================================================================================================

# COMPARISON SUMMARY
# Assignment (=)        -> NO copy (same reference)
# np.asarray()          -> No copy if possible
# np.copy()             -> ALWAYS creates a new array
# arr.copy()            -> Same as np.copy(arr)

Original Array: [1 2 3]
Copied Array: [99  2  3]

Do they share memory?
Same object: False
Same memory: False

Original 2D Array:
 [[1 2]
 [3 4]]
Copied 2D Array:
 [[10  2]
 [ 3  4]]

Fortran Ordered Copy:
Is F-contiguous: True
Is C-contiguous: False


NP.FROMITER()

NP.FROMFUNCTION()

NP.FROMSTRING()

NP.LOADTXT()

NP.GENFROMTXT()

NP.EMPTY()

In [ ]:
# numpy.empty((shape), dtype=float, order='C', like=None)
# create array of specific shape and data type with garbage values

# SHAPE PARAMETER
arr = np.empty((0))
print(arr, "\n")

arr = np.empty((3))
print(arr, "\n")

arr = np.empty((1, 2))
print(arr, "\n")

arr = np.empty((1, 1, 3))
print(arr, "\n")


# DTYPE PARAMETER
arr = np.empty((3), dtype='float')
print(arr, "\n")

arr = np.empty((3), dtype='int')
print(arr, "\n")

arr = np.empty((3), dtype='bool')
print(arr, "\n")

NP.EMPTY_LIKE()

NP.ZEROS()

NP.ZEROS_LIKE()

NP.ONES()

NP.ONES_LIKE()

NP.FULL()

NP.FULL_LIKE

NP.ARANGE()

NP.LINSPACE()

NP.LOGSPACE

NP.MESHGRID()

NP.MGRID()

NP.AGRID()

NP.DIAG

NP.DIAGFLAT

NP.TRI

NP.TRIL

NP.TRIU

# ARRAY PROPERTIES (not functions)

ARRAY.NDIM

In [37]:
# ndarray.ndim
# =================================================================================================================

# It returns integer representing the number of axes (dimensions) of the array
# =================================================================================================================

# DIMENSION VISUALIZATION:
# 0D -> Scalar (just a number)
# 1D -> Vector (a list of numbers)
# 2D -> Matrix (rows and columns)
# 3D -> Tensor (multiple matrices/layers)
# =================================================================================================================

# 0-DIMENSIONAL ARRAY (SCALAR)
scalar_arr = np.array(42)
print("0D Array:", scalar_arr)
print("Dimensions (ndim):", scalar_arr.ndim) # Output: 0
# =================================================================================================================

# 1-DIMENSIONAL ARRAY (VECTOR)
vector_arr = np.array([1, 2, 3, 4])
print("\n1D Array:", vector_arr)
print("Dimensions (ndim):", vector_arr.ndim) # Output: 1
# =================================================================================================================

# 2-DIMENSIONAL ARRAY (MATRIX)
# Created by passing a list of lists
matrix_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", matrix_arr)
print("Dimensions (ndim):", matrix_arr.ndim) # Output: 2
# =================================================================================================================

# 3-DIMENSIONAL ARRAY (TENSOR/CUBE)
# Created by passing a list of matrices
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", tensor)
print("Dimensions (ndim):", tensor.ndim) # Output: 3
# =================================================================================================================

# KEY DIFFERENCE: ndim vs shape
# ndim -> Tell you "how many" dimensions exist
# shape -> Tells you the "size" of each of those 

arr_example = np.zeros((2, 3, 4)) # A 3D array
print("\nComplex Array Details:")
print("Number of dimensions (ndim):", arr_example.ndim) # Output: 3
print("Shape of dimensions (shape):", arr_example.shape) # Output: (2, 3, 4)


0D Array: 42
Dimensions (ndim): 0

1D Array: [1 2 3 4]
Dimensions (ndim): 1

2D Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions (ndim): 3

Complex Array Details:
Number of dimensions (ndim): 3
Shape of dimensions (shape): (2, 3, 4)


ARRAY.SHAPE or NP.SHAPE()

In [41]:
# np.shape(a)
# array.shape
# =================================================================================================================

# MAIN FEATURE:
# It returns a tuple representing the size/length of each dimension of the array
# For a 1D array, it provides (length,)
# For a 2D array, it provides (rows, columns)
# For a 3D array, it provides (depth, rows, columns)
# =================================================================================================================

# SHAPE OF DIFFERENT DIMENSIONS
# 1D Array (Vector)
vector = np.array([1, 2, 3, 4, 5])
print("1D Shape:", vector.shape)  # Output: (5,) - Note the comma for a 1-element tuple
# =================================================================================================================

# 2D Array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Shape:", matrix.shape)  # Output: (2, 3) -> 2 rows, 3 columns
# =================================================================================================================

# 3D Array (Tensor)
tensor = np.zeros((2, 3, 4)) 
print("3D Shape:", tensor.shape)  # Output: (2, 3, 4) -> 2 planes, 3 rows, 4 columns
# =================================================================================================================

# MODifying THE SHAPE (Directly)
# You can change the shape of an array by assigning a new tuple to the shape attribute
# (Total number of elements must remain the same)
arr = np.array([1, 2, 3, 4, 5, 6])
print("\nBefore reshaping:", arr.shape)

arr.shape = (2, 3)  # as 2*3 = 6 elements
print("After reshaping attribute:")
print(arr)
print("New Shape:", arr.shape)
# =================================================================================================================

# DIFFERENCE: np.shape(arr) vs arr.shape
# np.shape()    -> function that can take lists or arrays as input
# arr.shape     -> attribute of the numpy array object

my_list = [1, 2, 3]
print("\nShape of a list using np.shape:", np.shape(my_list)) # Works on non-array objects

1D Shape: (5,)
2D Shape: (2, 3)
3D Shape: (2, 3, 4)

Before reshaping: (6,)
After reshaping attribute:
[[1 2 3]
 [4 5 6]]
New Shape: (2, 3)

Shape of a list using np.shape: (3,)


ARRAY.SIZE

In [42]:
# array.size
# =================================================================================================================

# MAIN FEATURE:
# It returns the TOTAL number of elements in the array
# It is equivalent to the product of all elements in the array's shape
# =================================================================================================================

# SIZE vs SHAPE vs NDIM:
# ndim  -> How many axes (3)
# shape -> The length of each axis (3, 4)
# size  -> The total count of items (12)
# =================================================================================================================

# SIZE OF DIFFERENT ARRAYS
# 1D Array
vec = np.array([10, 20, 30])
print("1D Vector Size:", vec.size)  # Output: 3
# =================================================================================================================

# 2D Array (Matrix)
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Matrix Size:", mat.size)  # Output: 6 (2 rows * 3 columns)
# =================================================================================================================

# 3D Array (Tensor)
# A (2, 2, 2) array has 2 * 2 * 2 = 8 elements
ten = np.zeros((2, 2, 2))
print("3D Tensor Size:", ten.size)  # Output: 8
# =================================================================================================================

# SIZE OF EMPTY ARRAYS
empty_arr = np.array([])
print("Empty Array Size:", empty_arr.size)  # Output: 0
# =================================================================================================================

# CALCULATING MEMORY USAGE
# You can use .size combined with .itemsize (bytes per element) to find the total memory used.
arr = np.array([1, 2, 3], dtype=np.int64)
total_bytes = arr.size * arr.itemsize
print(f"\nTotal elements: {arr.size}")
print(f"Bytes per element: {arr.itemsize}")
print(f"Total memory used: {total_bytes} bytes")

1D Vector Size: 3
2D Matrix Size: 6
3D Tensor Size: 8
Empty Array Size: 0

Total elements: 3
Bytes per element: 8
Total memory used: 24 bytes


ARRAY.DTYPE

In [ ]:
# array.dtype
# =================================================================================================================

# MAIN FEATURE:
# It returns the type of data stored in the array (integers, floats, booleans)
# Unlike standard Python lists, all elements in a NumPy array MUST be of the same dtype
# =================================================================================================================

# AUTOMATIC TYPE INFERENCE
# NumPy looks at your data and chooses the smallest/most appropriate type.
arr_int = np.array([1, 2, 3])
print("Inferred Integer:", arr_int.dtype)   # Usually int64 or int32

arr_float = np.array([1.0, 2.0, 3.5])
print("Inferred Float:", arr_float.dtype)    # Usually float64
# =================================================================================================================

# FORCING A SPECIFIC DTYPE
# You can use the 'dtype' parameter during creation to save memory or ensure precision
arr_forced = np.array([1, 2, 3], dtype='float32') 
print("\nForced float32:", arr_forced.dtype)
# =================================================================================================================

# COMMON NUMPY DTYPES:
# int64 / int32        -> Integers (whole numbers)
# float64 / float32    -> Decimals (floating point)
# bool                 -> True or False
# complex128           -> Complex numbers (a + bj)
# <U11                 -> Unicode strings
# =================================================================================================================

# TYPE CONVERSION (astype)
# To change the dtype of an existing array, use the .astype() method.
# Note: This creates a COPY of the array.
original = np.array([1.9, 2.1, 3.5])
as_ints = original.astype(np.int32) 

print("\nOriginal Float Array:", original)
print("Converted to Int:", as_ints)  # Note: It truncates (1.9 becomes 1)
# =================================================================================================================

# THE "UPCASTING" RULE:
# If you mix types (e.g., add a float to an int array), NumPy will automatically 
# "upcast" to the more complex type to prevent data loss
mixed = np.array([1, 2, 3]) + 0.5
print("\nMixed (int + float) result dtype:", mixed.dtype) # Results in float64

Inferred Integer: int64
Inferred Float: float64

Forced float32: float32

Original Float Array: [1.9 2.1 3.5]
Converted to Int: [1 2 3]

Mixed (int + float) result dtype: float64


ARRAY.ITEMSIZE

In [45]:
# array.itemsize
# =================================================================================================================

# MAIN FEATURE:
# It returns the length of ONE array element in BYTES
# It is determined by the array's dtype (float64 uses more bytes than int8)
# =================================================================================================================

# DIFFERENT DTYPES HAVE DIFFERENT ITEMSIZE:
# int8    -> 1 byte  (8 bits)
# int32   -> 4 bytes (32 bits)
# float64 -> 8 bytes (64 bits)
# =================================================================================================================

# COMPARING DIFFERENT DTYPES
# Integer array (64-bit)
arr_int = np.array([1, 2, 3], dtype=np.int64)
print("int64 itemsize:", arr_int.itemsize, "bytes")  # Output: 8

# Integer array (8-bit)
arr_small = np.array([1, 2, 3], dtype=np.int8)
print("int8 itemsize: ", arr_small.itemsize, "byte")   # Output: 1
# =================================================================================================================

# CALCULATING TOTAL MEMORY (nbytes)
# Total memory = number of elements (size) * size of one element (itemsize)
arr = np.ones((10, 10), dtype=np.float64)

calculated_total = arr.size * arr.itemsize
actual_total = arr.nbytes  # NumPy has a built-in property for this too!

print(f"\nArray Shape: {arr.shape}")
print(f"Itemsize: {arr.itemsize} bytes")
print(f"Total elements: {arr.size}")
print(f"Total Memory Usage: {actual_total} bytes (or {actual_total/1024:.2f} KB)")
# =================================================================================================================

# ITEMSIZE WITH STRINGS
# For strings, itemsize depends on the length of the longest string in the array.
str_arr = np.array(['apple', 'banana', 'cherry'])
print("\nString Array dtype:", str_arr.dtype)
print("String Array itemsize:", str_arr.itemsize, "bytes") # Calculated based on Unicode chars

int64 itemsize: 8 bytes
int8 itemsize:  1 byte

Array Shape: (10, 10)
Itemsize: 8 bytes
Total elements: 100
Total Memory Usage: 800 bytes (or 0.78 KB)

String Array dtype: <U6
String Array itemsize: 24 bytes


ARRAY.NBYTES

In [49]:
# array.nbytes
# =================================================================================================================

# MAIN FEATURE:
# It returns the TOTAL bytes consumed by the elements of the array
# It does NOT include the memory overhead of the Python object itself (just the data)
# =================================================================================================================

# THE MATHEMATICAL FORMULA:
# nbytes = array.size * array.itemsize
# =================================================================================================================

# COMPARING MEMORY FOOTPRINT
# Creating a 100-element array with different precisions
arr_64 = np.ones(100, dtype=np.float64)
arr_32 = np.ones(100, dtype=np.float32)

print(f"64-bit array (float64): {arr_64.nbytes} bytes") # 100 * 8 = 800
print(f"32-bit array (float32): {arr_32.nbytes} bytes") # 100 * 4 = 400
# =================================================================================================================

# MULTI-DIMENSIONAL MEMORY
# Memory is calculated on total elements, regardless of shape (2D, 3D)
matrix = np.zeros((10, 10), dtype=np.int32) # 100 elements
print(f"\n10x10 Int32 Matrix size: {matrix.size} elements")
print(f"Total memory (nbytes): {matrix.nbytes} bytes") # 100 * 4 = 400
# =================================================================================================================

# PRACTICAL USE: Memory Check
# Useful when working with large datasets to prevent "MemoryError"
big_arr = np.random.rand(1000, 1000) # 1 million floats
print(f"\nLarge Matrix Memory: {big_arr.nbytes / 1e6:.2f} MB")

64-bit array (float64): 800 bytes
32-bit array (float32): 400 bytes

10x10 Int32 Matrix size: 100 elements
Total memory (nbytes): 400 bytes

Large Matrix Memory: 8.00 MB


NP.T

In [52]:
# array.T
# =================================================================================================================

# MAIN FEATURE:
# It returns the Transpose of the array (swaps rows and columns)
# It is a "view" of the original array, meaning it does NOT create a copy of the data
# =================================================================================================================

# 2D ARRAY TRANSPOSE (The most common use)
# Rows become Columns, Columns become Rows
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print("Original Matrix (2x3):")
print(matrix)

matrix_T = matrix.T
print("\nTransposed Matrix (3x2):")
print(matrix_T)
# =================================================================================================================

# NO EFFECT ON 1D ARRAYS
# Transposing a 1D vector does nothing because there is only one axis.
vector = np.array([1, 2, 3])
print("\n1D Vector Shape:", vector.shape)
print("1D Transpose Shape:", vector.T.shape) # Still (3,)
# =================================================================================================================

# MEMORY: SHARED DATA
# Since .T is a view, changing the transpose changes the original!
original = np.array([[1, 1], [1, 1]])
transposed_view = original.T

transposed_view[0, 1] = 99

print("\nOriginal after changing its transpose:")
print(original) # The value at [1, 0] is now 99
# =================================================================================================================

# HIGHER DIMENSIONS (ND ARRAYS)
# For N-dimensional arrays, .T simply reverses the order of the axes.
# (Shape (2, 3, 4) becomes (4, 3, 2))
tensor = np.zeros((2, 3, 4))
print("\n3D Tensor original shape:", tensor.shape)
print("3D Tensor transposed shape:", tensor.T.shape)

Original Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transposed Matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]

1D Vector Shape: (3,)
1D Transpose Shape: (3,)

Original after changing its transpose:
[[ 1  1]
 [99  1]]

3D Tensor original shape: (2, 3, 4)
3D Tensor transposed shape: (4, 3, 2)


ARRAY.REAL

In [4]:
# array.real
# =================================================================================================================

# MAIN FEATURE:
# It returns the real part of the complex numbers in the array
# If the array contains only real numbers (like integers or standard floats), it returns the array itself (or a view of it)
# =================================================================================================================

# WORKING WITH COMPLEX NUMBERS
# Complex numbers are represented as 'a + bj' where 'a' is the real part
c_arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])

print("Complex Array:", c_arr)
print("Real Part (.real):", c_arr.real) # Output: [1. 3. 5.]
# =================================================================================================================

# TYPE TRANSFORMATION
# The dtype of .real is typically the floating-point equivalent of the complex type e.g., complex128 (64-bit real + 64-bit imaginary) -> float64
print("\nOriginal dtype:", c_arr.dtype)      # complex128
print("Real part dtype:", c_arr.real.dtype)  # float64
# =================================================================================================================

# MODIFYING THE REAL PART (View vs Copy)
# .real returns a VIEW (Modifying it will change the original complex array)
c_num = np.array([1 + 5j, 2 + 5j])
real_view = c_num.real

real_view[0] = 99  # Changing the real part only

print("\nModified Real View:", real_view)
print("Updated Original Complex Array:", c_num) # Output: [99.+5.j, 2.+5.j]
# =================================================================================================================

# USE WITH NON-COMPLEX ARRAYS
# If the array is already real (e.g., int or float), .real simply returns a view.
standard_arr = np.array([10, 20, 30])
print("\nStandard Array .real:", standard_arr.real) # Output: [10, 20, 30]

Complex Array: [1.+2.j 3.+4.j 5.+6.j]
Real Part (.real): [1. 3. 5.]

Original dtype: complex128
Real part dtype: float64

Modified Real View: [99.  2.]
Updated Original Complex Array: [99.+5.j  2.+5.j]

Standard Array .real: [10 20 30]


ARRAY.IMAG

In [6]:
# array.imag
# =================================================================================================================

# MAIN FEATURE:
# It returns the imaginary part of the complex numbers in the array
# For real-valued arrays (integers, floats), it returns an array of zeros of the same shape and precision
# =================================================================================================================

# WORKING WITH COMPLEX NUMBERS
# Complex numbers are 'a + bj' where 'b' is the imaginary part
c_arr = np.array([1 + 2j, 3 + 4.5j, 5 - 1j])

print("Complex Array:", c_arr)
print("Imaginary Part (.imag):", c_arr.imag) # Output: [ 2.   4.5 -1. ]
# =================================================================================================================

# TYPE AND MEMORY
# Like .real, .imag returns a VIEW. 
# Modifying .imag changes the imaginary component of the original array
c_num = np.array([10 + 10j])
imag_view = c_num.imag

imag_view[0] = 0  # Setting the imaginary part to zero

print("\nUpdated Original Array:", c_num) # Output: [10.+0.j]
# =================================================================================================================

# IMAGINARY PART OF REAL ARRAYS
# If you call .imag on a standard integer or float array, it creates 
# an array of zeros of the same shape and precision.
real_arr = np.array([1, 2, 3], dtype=np.float64)
print("\nReal Array .imag:", real_arr.imag) # Output: [0. 0. 0.]
# =================================================================================================================

# COMMON COMPLEX ATTRIBUTES & FUNCTIONS
# 1. .real       -> Real component
# 2. .imag       -> Imaginary component
# 3. np.abs()    -> Magnitude (sqrt(a^2 + b^2))
# 4. np.angle()  -> Phase angle in radians

Complex Array: [1.+2.j  3.+4.5j 5.-1.j ]
Imaginary Part (.imag): [ 2.   4.5 -1. ]

Updated Original Array: [10.+0.j]

Real Array .imag: [0. 0. 0.]


ARRAY.FLAT

In [9]:
# array.flat
# =================================================================================================================

# MAIN FEATURE:
# It returns a 1D ITERATOR (view) over the array, regardless of the array's original shape
# It allows you to treat any multi-dimensional array as if it were a simple 1D list
# The size of number of elements remains the same
# =================================================================================================================

# BASIC ITERATION
# Useful for loops where you don't care about the rows/columns
matrix = np.array([[1, 2], 
                   [3, 4]])

print("Iterating through 2D matrix using .flat:")
for item in matrix.flat:
    print(item, end=" ")  # Output: 1 2 3 4
print("\n")
# =================================================================================================================

# ACCESSING BY INDEX
# You can use .flat to get the "Nth" element of an array without knowing its coordinates
tensor = np.random.randint(0, 10, (2, 3, 4)) # A complex 3D shape
print("Element at index 5 in flattened view:", tensor.flat[5])
# =================================================================================================================

# ASSIGNMENT
# You can modify elements in the original array using the flat iterator
arr = np.zeros((2, 2))
arr.flat = [10, 20, 30, 40]  # Overwrites all elements

print("Array after flat assignment:")
print(arr)
# =================================================================================================================

# flat vs flatten() vs ravel()
# 1. arr.flat       -> An ITERATOR (Memory efficient, does not create a new array)
# 2. arr.flatten()  -> Returns a 1D COPY (Changes don't affect the original)
# 3. arr.ravel()    -> Returns a 1D VIEW (Changes DO affect the original)

# Example of flat vs flatten
example = np.array([[1, 2], [3, 4]])
f_copy = example.flatten()
f_copy[0] = 99

print("\nOriginal after flatten copy change:\n", example) # Still 1 (Copy)

example.flat[0] = 99
print("Original after .flat assignment:\n", example)   # Now 99 (View/Iterator)
# =================================================================================================================

# WHY USE .flat:
# ✔ When you need to loop over every single element but the shape doesn't matter.
# ✔ To bulk-assign values from a list to a multi-dimensional array.
# ✔ Performance: It avoids creating a large 1D copy in memory.

Iterating through 2D matrix using .flat:
1 2 3 4 

Element at index 5 in flattened view: 0
Array after flat assignment:
[[10. 20.]
 [30. 40.]]

Original after flatten copy change:
 [[1 2]
 [3 4]]
Original after .flat assignment:
 [[99  2]
 [ 3  4]]


# ARRAY ALTERATIONS

NP.RESHAPE()

In [ ]:
# np.reshape(arr, (newshape), order='C')
# =================================================================================================================

# MAIN FEATURE:
# It gives a new shape to an array without changing its data
# Returna a view of the original array whenever possible (no data copy)
# The total number of elements (size) MUST remain the same
# The product of the new shape dimensions must equal the number of elements in the original array
# =================================================================================================================

# ARR (required): Input array whose shape need to change
# NEWSHAPE (required): New shape dimensions (product of new shape all dimensions = number of elements in array)
# NEWSHAPE: Value of newshape = -1 means auto-calculate this dimension based on the other given dimensions
# ORDER (optional): Controls how array elements are arranged in memory
#                  'C' → Stores data row by row (last index changes fastest), standard in Python
#                  'F' → Stores data column by column (first index changes fastest), used in Fortran
#                  'A' → Chooses 'F' if the input is already Fortran-contiguous, otherwise uses 'C'
#                  'K' → Preserves the original memory order as closely as possible (default)

# =================================================================================================================

# BASIC RESHAPING
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original 1D:", arr)

# 1D to 2D (Rows, Cols)
arr_2d = np.reshape(arr, (3, 4))
print("\nReshaped to 3x4:\n", arr_2d)

# 2D to 3D (Planes, Rows, Cols)
arr_3d = np.reshape(arr, (2, 3, 2))
print("\nReshaped to 2x3x2:\n", arr_3d)
# =================================================================================================================

# THE "-1" TRICK (AUTO-CALCULATION)
# If you provide -1 for one dimension, NumPy automatically calculates the correct value
# (12 elements / 2 rows = 6 columns)
auto_reshape = np.reshape(arr, (2, -1))
print("\nAuto-calculated columns (2, -1):", auto_reshape.shape) # Result: (2, 6)

# Flattening using -1
flattened = np.reshape(arr_2d, (-1))
print("Flattened using -1:", flattened.shape) # Result: (12,)
# =================================================================================================================

# MEMORY ORDER ('C' vs 'F')
# 'C' (Default): Fills row by row
c_order = np.reshape(arr, (3, 4), order='C')
# 'F': Fills column by column
f_order = np.reshape(arr, (3, 4), order='F')

print("\nC-Order (Row-wise):\n", c_order[0]) # Elements 1, 2, 3, 4 are in row 0
print("F-Order (Column-wise):\n", f_order[:, 0]) # Elements 1, 2, 3 are in col 0
# =================================================================================================================

# VIEW VS COPY:
# Reshape usually returns a VIEW (it points to the same memory)
# If you change the reshaped array, the original changes!
original = np.array([1, 2, 3, 4])
reshaped_view = np.reshape(original, (2, 2))
reshaped_view[0, 0] = 99

print("\nOriginal after changing reshaped view:", original[0]) # Output: 99
# =================================================================================================================

# WHEN TO USE np.reshape:
# ✔ To prepare data for Machine Learning models (e.g., adding a channel dimension to images)
# ✔ To convert flat data from a file into a structured grid/matrix
# ✔ To perform operations across specific axes by restructuring the data layout

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x3x2:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Auto-calculated columns (2, -1): (2, 6)
Flattened using -1: (12,)

C-Order (Row-wise):
 [1 2 3 4]
F-Order (Column-wise):
 [1 2 3]

Original after changing reshaped view: 99


NP.RESIZE()

In [ ]:
# np.resize(arr, (newshape), order='C')
# changes the shape of given array
# elements ≤ product of dimensions (if elements less than size them elements repeated to get fill in new shape)


# ARR (required): Input array whose shape need to change
# NEWSHAPE (required): New shape dimensions (product of new shape all dimensions) may or may not equal to number of elements in array)
# NEWSHAPE: Value of newshape = -1 mean convert any array to 1D array
# ORDER (optional):


# RETURNS new array with given shape


arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
print(arr, "\n")

arr = np.resize(arr, (2, 3))
print(arr.shape)
print(arr, "\n")

arr = np.resize(arr, (3, 4))
print(arr.shape)
print(arr, "\n")


arr = np.resize(arr, (2, 3, 2))
print(arr.shape)
print(arr, "\n")

(6,)
[1 2 3 4 5 6] 

(2, 3)
[[1 2 3]
 [4 5 6]] 

(3, 4)
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]] 

(2, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]] 



NP.REVAL()

In [ ]:
# np.ravel(arr, order='C')
# convert the given nD array to 1D array


# ARR (required): Input array whose shape need to change
# ORDER (optional):


# RETURNS new 1D array


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
arr = np.ravel(arr)
print(arr, "\n")

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)
arr = np.ravel(arr)
print(arr, "\n")

(2, 3)
[1 2 3 4 5 6] 

(2, 2, 2)
[1 2 3 4 5 6 7 8] 



NP.FLATTEN()

In [ ]:
# arr.flatten(order='C')
# convert the nD array to 1D array


# ARR (required): Input array whose shape need to change
# ORDER (optional):

# WORK AS arr.flatten not as np.flatten
# RETURNS new 1D array


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
arr = arr.flatten()
print(arr, "\n")

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)
arr = arr.flatten()
print(arr, "\n")

(2, 3)
[1 2 3 4 5 6] 

(2, 2, 2)
[1 2 3 4 5 6 7 8] 



NP.TRANSPOSE()

NP.SWAPAXES()

NP.ROLLAXIS()

NP.MOVEAXIS()

NP.EXPAND_DIMS()

NP.SQWEEZE()

NP.ASFARRAY()

NP.ASTYPE()

NP.VIEW()

NP.MATRIX()

# ARRAY INDEXING & SLICING

NP.TAKE()

NP.PUT()

NP.WHERE()

NP.ANYWHERE()

NP.FLATNONZERO()

NP.COMPRESS()

NP.CHOOSE()

STANDARD SLICING

ADVANCE SLICING

BOOLEAN SLICING

FANCY SLICING

# ARRAY COMBINING & SPLITTING

NP.CONCATENATE()

NP.STACK()

NP.VSTACK()

NP.HSTACK()

NP.DSTACK()

NP.COLUMNSTACK()

NP.ROWSTACK()

NP.BLOCK()

NP.SPLIT()

NP.ARRAY_SPLIT()

NP.VSPLIT()

NP.HSPLIT()

NP.DSPLIT()

# ARRAY COPYING & SORTING

NP.COPY()

NP.SORT()

NP.ARGSORT()

NP.LEXSORT()

NP.PARTITION()

NP.ARGPARTITION()

# SEARCH, COUNT & CONDITIONS CHECK

NP.WHERE()

NP.ARGMAX()

NP.ARGMIN()

NP.AMAX()

NP.AMIN()

NP.NANARGMAX()

NP.NANARGMIN()

NP.SEARCHSORTED()

NP.EXTRCT()

NP.COUNR_NONZERO()

NP.ANY()

NP.ALL()

# RANDOM MODULE

### RANDOM ARRAY CREATION

### PERMUTATIONS AND SHUFFLE

### DISTRIBUTIONS

# LINALG MODULE

### VECTOR & MATRIX PRODUCTS

### NORMA & DISTANCES

### SOLVING LINEAR SYSTEMS

### INVERSE & PSEUDO INVERSE

### DETERMINANTS

### EIGENVALUES & EIGENVECTORS

### SINGULAR VALUE DECOMPOSITION

### MATRIX FACTORIZATION & MISC

### TENSOR OPERATIONS